{{- range $key, $val := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
    spec:
      containers:
        - name: {{ $key }}
          image: {{ $val.image }}
          ports:
            - containerPort: {{ $val.port }}
          {{- if eq $key "mariadb_db" }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ $.Values.database.password | quote }}
            - name: MYSQL_DATABASE
              value: {{ $.Values.database.name | quote }}
            - name: MYSQL_USER
              value: {{ $.Values.database.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ $.Values.database.password | quote }}
          {{- end }}
          {{- if eq $key "php_fpm" }}
          env:
            - name: DB_HOST
              value: "mariadb_db"
            - name: DB_DATABASE
              value: {{ $.Values.database.name | quote }}
            - name: DB_USERNAME
              value: {{ $.Values.database.user | quote }}
            - name: DB_PASSWORD
              value: {{ $.Values.database.password | quote }}
            - name: REDIS_HOST
              value: "redis_cache"
            - name: WA_API_KEY
              value: {{ $.Values.waApiKey | default "" | quote }}
            - name: VA_PREFIX_ALIYAH
              value: "988"
            - name: VA_CLIENT_ID_ALIYAH
              value: "19104"
            - name: VA_SECRET_KEY_ALIYAH
              value: {{ $.Values.vaSecretKeyAliyah | default "" | quote }}
            - name: VA_PREFIX_TSANAWIYAH
              value: "988"
            - name: VA_CLIENT_ID_TSANAWIYAH
              value: "60109"
            - name: VA_SECRET_KEY_TSANAWIYAH
              value: {{ $.Values.vaSecretKeyTsanawiyah | default "" | quote }}
            - name: VA_PREFIX_MAHAD_ALY
              value: "988"
            - name: VA_CLIENT_ID_MAHAD_ALY
              value: "80109"
            - name: VA_SECRET_KEY_MAHAD_ALY
              value: {{ $.Values.vaSecretKeyMahadAly | default "" | quote }}
            - name: VA_HOST_URL
              value: "https://api.bni-ecollection.com/"
          {{- end }}
{{- end }}
